<template>
  <div id="dashboard">
    
    <el-row class="content-container">
      <el-col class="content-container__info">
        <div class="content-container__info__title">WELCOME TO THE SPARC DATAPORTAL</div>
        <div class="content-container__info__text">The Sparc Dataportal is an easily accessible resource to find, visualize and access data generated by the NIH SPARC project.</div>
      </el-col>
      <el-col>
        <sparc-datasets />
      </el-col>
    </el-row>
    <sprc-stats />
  </div>
</template>

<script>
import BfVega from './components/bf-vega/BfVega.vue'
import SparcWelcome from './components/sparc-welcome/SparcWelcome.vue'
import SprcStats from './components/SprcStats/SprcStats.vue'
import SparcDatasets from './components/sparc-datasets/SparcDatasets.vue'

export default {
  name: 'dashboard',
  components: {
    BfVega,
    SparcWelcome,
    SprcStats,
    SparcDatasets
  }
}
</script>

<style lang="scss" scoped>
@import '../../../static/css/_variables.scss';

  #dashboard {
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    text-align: center;
    color: $vestibular; 
  }
  .content-container {
    display:flex;
    border-bottom: 1px solid lightgray;

    .content-container__info {
      flex-basis: 400px;
      min-height: 700px;
      color: $text-color;
      padding: 8px 20px;
      border-right: 1px solid lightgray;

      .content-container__info__title {
        text-align: center;
        margin-bottom: 16px;
        margin-top: 8px;
      }

      .content-container__info__text {
        text-align: justify;
        font-size: 14px;
      }

    }
  }
</style>
